server:
  port: 6066
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  jackson:
    date-format: yyyy.MM.dd HH:mm
    time-zone: "GMT+8"
  datasource:
    #    username: root
    #    password: ljkroot
    #    url: jdbc:mysql://localhost:3306/vive?useUnicode=false&characterEncoding=UTF-8
    #    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: DoDo1306
    url: jdbc:mysql://rm-2zenq2aelig11p0u0o.mysql.rds.aliyuncs.com:3306/cloud_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #监控统计拦截的filters
    filters: stat,wall
    #druid配置
    #配置初始化大小/最小/最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000
    #间隔多久进行一次检测，检测需要关闭的空闲连接
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties:
      druid:
        stat:
          mergeSql: true
          slowSqlMillis: 5000

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.webserver.dao
  configuration:
    map-underscore-to-camel-case: true